# Generated by Django 4.2.7 on 2023-12-22 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_num', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_num', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_num', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.grade')),
                ('lessons', models.ManyToManyField(related_name='units', to='app.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.TextField()),
                ('num_answer', models.IntegerField()),
                ('answer_a', models.CharField(max_length=255, null=True)),
                ('answer_b', models.CharField(max_length=255, null=True)),
                ('answer_c', models.CharField(max_length=255, null=True)),
                ('answer_d', models.CharField(max_length=255, null=True)),
                ('letter_answer', models.CharField(default='a', max_length=1)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='problems',
            field=models.ManyToManyField(related_name='lessons', to='app.problem'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.unit'),
        ),
        migrations.AddField(
            model_name='grade',
            name='units',
            field=models.ManyToManyField(related_name='grades', to='app.unit'),
        ),
    ]
