# Generated by Django 4.2.7 on 2023-12-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade_num',
            new_name='grade_id',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_num',
            new_name='lesson_id',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='unit_num',
            new_name='unit_id',
        ),
    ]
