# Generated by Django 4.2.7 on 2023-12-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_grade_num_grade_grade_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='letter_answer',
        ),
    ]
